language: node_js
node_js:
  - "6.1"

services:
  - mongodb

# See: https://docs.travis-ci.com/user/languages/javascript-with-nodejs/#Meteor-Apps
env:
  - CXX=g++-4.8
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8